export const ACCOUNT_CREATE_REQUEST     = 'ACCOUNT_CREATE_REQUEST';
export const ACCOUNT_CREATE_SUCCESS     = 'ACCOUNT_CREATE_SUCCESS';
export const ACCOUNT_CREATE_FAIL        = 'ACCOUNT_CREATE_FAIL';