export const ACCOUNT_CREATE_REQUEST     = 'ACCOUNT_CREATE_REQUEST';
export const ACCOUNT_CREATE_SUCCESS     = 'ACCOUNT_CREATE_SUCCESS';
export const ACCOUNT_CREATE_FAIL        = 'ACCOUNT_CREATE_FAIL';

export const ACCOUNT_LIST_REQUEST       = 'ACCOUNT_LIST_REQUEST';
export const ACCOUNT_LIST_SUCCESS       = 'ACCOUNT_LIST_SUCCESS';
export const ACCOUNT_LIST_FAIL          = 'ACCOUNT_LIST_FAIL';

export const ACCOUNT_DEPOSIT_REQUEST    = 'ACCOUNT_DEPOSIT_REQUEST';
export const ACCOUNT_DEPOSIT_SUCCESS    = 'ACCOUNT_DEPOSIT_SUCCESS';
export const ACCOUNT_DEPOSIT_FAIL       = 'ACCOUNT_DEPOSIT_FAIL';