export const TRANSACTION_LIST_REQUEST   = "TRANSACTION_LIST_REQUEST";
export const TRANSACTION_LIST_SUCCESS   = "TRANSACTION_LIST_SUCCESS";
export const TRANSACTION_LIST_FAIL      = "TRANSACTION_LIST_FAIL";

export const TRANSFER_REQUEST           = "TRANSFER_REQUEST";
export const TRANSFER_SUCCESS           = "TRANSFER_SUCCESS";
export const TRANSFER_FAIL              = "TRANSFER_FAIL";